language: go

go:
  - 1.12

env:
  - GO111MODULE=on

before_script:
  - make download
  - make install

script:
  - gofmt -s -l .
  - go vet ./...
  - golint -set_exit_status $(go list ./...)
  - go test -race -coverprofile=coverage.txt -covermode=atomic

