language: go

go:
  - 1.12

before_script:
  - make download
  - go get golang.org/x/lint/golint

script:
  - gofmt -s -l .
  - go vet ./...
  - golint -set_exit_status $(go list ./...)
  - go test -race -coverprofile=coverage.txt -covermode=atomic

